CREATE SCHEMA IF NOT EXISTS core_rating;

DROP TABLE IF EXISTS core_rating.ratings;

CREATE TABLE if not exists core_rating.ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    mark VARCHAR NOT NULL,
    CONSTRAINT unique_user_likes_event UNIQUE (user_id, event_id)
);