CREATE SCHEMA IF NOT EXISTS core_requests;

DROP TABLE IF EXISTS core_requests.requests;

CREATE TABLE IF NOT EXISTS core_requests.requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT UNIQUE_EVENT_REQUESTER UNIQUE (requester_id, event_id)
);