CREATE SCHEMA IF NOT EXISTS core_events;

DROP TABLE IF EXISTS core_events.categories, core_events.events, core_events.compilations,
core_events.compilations_events;

CREATE TABLE IF NOT EXISTS core_events.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS core_events.events(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation TEXT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES core_events.categories(id),
    created_on TIMESTAMP NOT NULL,
    event_date TIMESTAMP NOT NULL,
    description TEXT NOT NULL,
    initiator_id BIGINT NOT NULL,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    published_on TIMESTAMP,
    request_moderation BOOLEAN NOT NULL,
    state VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE if not exists core_events.compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_pinned BOOLEAN NOT NULL,
    title VARCHAR(50) NOT NULL
);

CREATE TABLE if not exists core_events.compilations_events (
    compilation_id BIGINT NOT NULL REFERENCES core_events.compilations(id) on delete cascade,
    event_id BIGINT NOT NULL REFERENCES core_events.events(id) on delete cascade,
    PRIMARY KEY (compilation_id, event_id)
);
